name: Sync to Private Repo
on: 
  push:
    branches:
      - AbstractionSyntaxTree
  pull_request:
    branches:
      - AbstractionSyntaxTree

jobs:
  git-sync:
    runs-on: ubuntu-latest
    environment: Sync Environment  # Create the environment variable to use
    steps:
      #- name: Checkout repository
      #uses: actions/checkout@v2
      #with:
      #persist-credentials: false
      - name: Sync to Private Repo
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:alphastigma101/Compiler.git"
          source_branch: "AbstractionSyntaxTree"
          destination_repo: "git@github.com:alphastigma101/Private-Projects.git"
          destination_branch: "refs/heads/compiler"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
