name: Sync to Private Repo
on: 
  push:
    branches:
      - AbstractionSyntaxTree
  pull_request:
    branches:
      - AbstractionSyntaxTree

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: Sync Environment  # Create the environment name
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Sync to Private Repo
        uses: wei/git-sync@v3
        env:
          PUBLIC_REPO_PAT: ${{ secrets.PUBLIC_REPO_PAT }}
        with:
          source_repo: "https://github.com/alphastigma101/Compiler.git"
          source_branch: "AbstractionSyntaxTree"
          destination_repo: "https://alphastigma101:${{ env.PUBLIC_REPO_PAT }}@github.com/alphastigma101/Private-Projects.git"
          destination_branch: "compiler"
            #github_token: ${{ env.PUBLIC_REPO_PAT }}
